<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>request on Seiri&#39;s Blog</title>
    <link>https://seiri-blog.github.io/tags/request/</link>
    <description>Recent content in request on Seiri&#39;s Blog</description>
    <generator>Hugo -- gohugo.io</generator>
    <copyright>2024 Seiri All rights reserved</copyright>
    <lastBuildDate>Tue, 26 Dec 2023 12:04:33 +0900</lastBuildDate><atom:link href="https://seiri-blog.github.io/tags/request/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>PythonでRetry Request Utilityを作成する方法</title>
      <link>https://seiri-blog.github.io/posts/python-retry-request/</link>
      <pubDate>Tue, 26 Dec 2023 12:04:33 +0900</pubDate>
      
      <guid>https://seiri-blog.github.io/posts/python-retry-request/</guid>
      <description>はじめに Python を使用して API リクエストを行う際、アプリケーションの信頼性はネットワークの問題やサーバーエラーによって挑戦されることがあります。本記</description>
    </item>
    
  </channel>
</rss>
